### ISSUE TITLE
"sysm" module error

### ISSUE THREAD

**Issue by ghost** [mills-lab/vapor#2]
I'm trying to run vapor on a vcf file, and I'm getting the following error:

`Traceback (most recent call last):
  File "/root/.local/bin/vapor", line 4, in <module>
    __import__('pkg_resources').run_script('VaPoR==0.0.1', 'vapor')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1623, in run_script
    exec(script_code, namespace, namespace)
  File "/root/.local/lib/python2.7/site-packages/VaPoR-0.0.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/vapor", line 295, in <module>

  File "/root/.local/lib/python2.7/site-packages/VaPoR-0.0.1-py2.7-linux-x86_64.egg/vapor_vali/Simple_function.py", line 7, in <module>
  File "/root/.local/lib/python2.7/site-packages/VaPoR-0.0.1-py2.7-linux-x86_64.egg/vapor_vali/Simple_function.py", line 6, in __bootstrap__
  File "vapor_vali/Simple_function.pyx", line 3, in init vapor_vali.Simple_function (vapor_vali/Simple_function.c:75953)
ImportError: No module named sysm`

Looking online, I cannot find any such module named "sysm". Please let me know what I need to install to resolve this error.

**Comment by xuefzhao** [comment]
this is a cython problem , where in some operating systems, if you code something like:  'import sys, os' , cython wouldn't be able to recognize 'sys' but interprete as 'sysm'. I have changed the Simple_function.pyx, simply put 'import os' and 'import sys' in two different lines.   If you renew your version, or just manually change your Simply_function.pyx in the same way, the error should go away. please let me know if this works.

Best,

Xuefang

**Comment by ghost** [comment]
Thanks @xuefzhao, I think I've fixed all my problems with required dependencies (which btw, there were many of that were not mentioned in the README, including scikit-learn, R, freetype, and libpng. Please consider mentioning these in the "Required third-party resources" section).

I did, however, receive another error with the code itself while trying to run it. I'll open another ticket for that and close this one, as it is unrelated to this issue.
