### ISSUE TITLE
vapor script: local variable 'info' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [mills-lab/vapor#3]
I received the following error while trying to run vapor on a vcf file:
```
Traceback (most recent call last):
  File "/root/.local/bin/vapor", line 4, in <module>
    __import__('pkg_resources').run_script('VaPoR==0.0.1', 'vapor')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1623, in run_script
    exec(script_code, namespace, namespace)
  File "/root/.local/lib/python2.7/site-packages/VaPoR-0.0.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/vapor", line 302, in <module>

  File "/root/.local/lib/python2.7/site-packages/VaPoR-0.0.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/vapor", line 287, in vcf_list_readin

UnboundLocalError: local variable 'info' referenced before assignment
```
Looking at [line 287 of vapor](https://github.com/mills-lab/vapor/blob/master/vapor_vali/vapor#L287), it appears the code does not account for if the "Other" field does not appear in the INFO column. The vcf file I'm using is the output of running Manta on a BAM file, which does not include this. The Manta output format is detailed here: https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#manta-vcf-reporting-format.

Also, can you please let me know if vapor supports multi-sample vcf files? The vcf I'm using consists of 3 samples created from 3 different BAM files, so should I use the "--pacbio-input" parameter 3 times, one with each bam file?

**Comment by xuefzhao** [comment]
so the 'other' option is only used if the svtype listed in vcf is beyond the scope of  ' DEL','INV','INS',' DISDUP', 'TANDUP', and the couple complex format we defined.  I would suggest you to transfer vcf to bed and work with those for now. I am also working on the vcf part, trying to make it as inclusive as possible.

**Comment by xuefzhao** [comment]
and vapor do not work with multi-sample vcf files, so to run multiple samples, you want them each in different vcf file then apply vapor
